spring:
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      region:
        static: ${AWS_REGION}
  config:
    import: aws-secretsmanager:secret-name

com:
  upwork:
    sns:
      topic-arn: ${SNS_TOPIC_ARN}
    sqs:
      queue-url: ${SQS_QUEUE_URL}