spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      secretsmanager:
        reload:
          strategy: refresh
          period: 20s
  config:
    import: aws-secretsmanager:${AWS_SECRET_NAME}

com:
  upwork:
    sns:
      topic-arn: ${SNS_TOPIC_ARN}
    sqs:
      queue-url: ${SQS_QUEUE_URL}