spring:
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      sns:
        region: ${AWS_REGION}
      sqs:
        region: ${AWS_REGION}

com:
  upwork:
    sns:
      topic-arn: arn:aws:sns:region-code:account-id:topic-name
    sqs:
      queue-url: https://sqs.region-code.amazonaws.com/account-id/queue-name