spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG