spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

com:
  upwork:
    storage:
      s3:
        bucket-name: ${S3_BUCKET_NAME}